/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplateIdRouteImport } from './routes/template.$id'
import { Route as BuyIdRouteImport } from './routes/buy.$id'
import { Route as AuthenticatedQuickstoreRouteImport } from './routes/_authenticated/quickstore'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStoreProjectIdRouteImport } from './routes/_authenticated/store.$projectId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIdRoute = TemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIdRoute = BuyIdRouteImport.update({
  id: '/buy/$id',
  path: '/buy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuickstoreRoute = AuthenticatedQuickstoreRouteImport.update({
  id: '/quickstore',
  path: '/quickstore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreProjectIdRoute =
  AuthenticatedStoreProjectIdRouteImport.update({
    id: '/store/$projectId',
    path: '/store/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/builder': typeof BuilderRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/quickstore': typeof AuthenticatedQuickstoreRoute
  '/buy/$id': typeof BuyIdRoute
  '/template/$id': typeof TemplateIdRoute
  '/store/$projectId': typeof AuthenticatedStoreProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/builder': typeof BuilderRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/quickstore': typeof AuthenticatedQuickstoreRoute
  '/buy/$id': typeof BuyIdRoute
  '/template/$id': typeof TemplateIdRoute
  '/store/$projectId': typeof AuthenticatedStoreProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/builder': typeof BuilderRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/quickstore': typeof AuthenticatedQuickstoreRoute
  '/buy/$id': typeof BuyIdRoute
  '/template/$id': typeof TemplateIdRoute
  '/_authenticated/store/$projectId': typeof AuthenticatedStoreProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/builder'
    | '/features'
    | '/pricing'
    | '/sitemap.xml'
    | '/templates'
    | '/dashboard'
    | '/quickstore'
    | '/buy/$id'
    | '/template/$id'
    | '/store/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/builder'
    | '/features'
    | '/pricing'
    | '/sitemap.xml'
    | '/templates'
    | '/dashboard'
    | '/quickstore'
    | '/buy/$id'
    | '/template/$id'
    | '/store/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/builder'
    | '/features'
    | '/pricing'
    | '/sitemap.xml'
    | '/templates'
    | '/_authenticated/dashboard'
    | '/_authenticated/quickstore'
    | '/buy/$id'
    | '/template/$id'
    | '/_authenticated/store/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuilderRoute: typeof BuilderRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplatesRoute: typeof TemplatesRoute
  BuyIdRoute: typeof BuyIdRoute
  TemplateIdRoute: typeof TemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$id': {
      id: '/template/$id'
      path: '/template/$id'
      fullPath: '/template/$id'
      preLoaderRoute: typeof TemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$id': {
      id: '/buy/$id'
      path: '/buy/$id'
      fullPath: '/buy/$id'
      preLoaderRoute: typeof BuyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quickstore': {
      id: '/_authenticated/quickstore'
      path: '/quickstore'
      fullPath: '/quickstore'
      preLoaderRoute: typeof AuthenticatedQuickstoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store/$projectId': {
      id: '/_authenticated/store/$projectId'
      path: '/store/$projectId'
      fullPath: '/store/$projectId'
      preLoaderRoute: typeof AuthenticatedStoreProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedQuickstoreRoute: typeof AuthenticatedQuickstoreRoute
  AuthenticatedStoreProjectIdRoute: typeof AuthenticatedStoreProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedQuickstoreRoute: AuthenticatedQuickstoreRoute,
  AuthenticatedStoreProjectIdRoute: AuthenticatedStoreProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuilderRoute: BuilderRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplatesRoute: TemplatesRoute,
  BuyIdRoute: BuyIdRoute,
  TemplateIdRoute: TemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
